insert into currency_exchange(CONVERSION_MULTIPLE,ID,CURRENCY_FROM,CURRENCY_TO,ENVIRONMENT)
VALUES(65,10001,'USD','INR','');
insert into currency_exchange(CONVERSION_MULTIPLE,ID,CURRENCY_FROM,CURRENCY_TO,ENVIRONMENT)
VALUES(75,10002,'EUR','INR','');
insert into currency_exchange(CONVERSION_MULTIPLE,ID,CURRENCY_FROM,CURRENCY_TO,ENVIRONMENT)
VALUES(25,10003,'AUD','INR','');